arb-dir: lib/core/localization/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localization/generated
nullable-getter: false
required-resource-attributes: true
format: true
preferred-supported-locales:
  - zh
  - en
use-deferred-loading: false
